### ISSUE TITLE
getting acess denied 

### ISSUE THREAD

**Issue by mukaramkhaleel** [austincunningham/keycloak-express#4] opened 2018-10-31 10:25 UTC
hi,
i followed you app and finally i got http://localhost:8000/test?auth_callback=1&state=a99b790d-2d31-44cb-8b6e-6e3140366743&session_state=2134e9c3-c3f7-4248-9252-00ee60275ceb&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..1ijqAFXLmB7kG7siyVdidw.r1ZVpw3sz14S-Zrhvmntymc-fnGJCs9WMYMmeC6pV2XYGkLNlSyWnsX-PukdTtXIg91JMDyKoNZZyo4Un8ktfd9rbunjErrb7MMt4jOqfanF2HgWkxFvWH9RailbCd9TpFgv6-E3ywTyai-4iR4uZtLRi8C-SRTxf4liduHoDykxRWpfZYWagyxcvEV4iWulOQ32ATyrVpxAAZ9eBPi0UARG80KqwaojjUZZLQRIfRNuErW2bWmaYexETuoohhMF.VSZRDUdXCFLBaICUcN02LA
error was access denied

**Comment by austincunningham** [comment] 2020-03-18 11:09
Apologies haven't been checking issues on this repo. Not able to reproduce this issue may have been fixed in the mean time. Closing.

**Closed as completed by austincunningham** 2020-03-18 11:09 UTC
